- bullet:
  - level1: on
    level2: off

- lang: off
  list:
  - title: Español
    path: es
  - title: English
    path: en

- versions: off
  list:
  - title: v1.0
    path: v1.0
  - title: v2.0
    path: v2.0