title: GitOwl Framework
logo: <img src="themes/default/img/logo.svg"/>
theme: default
redirectHome: true
nav:
  prev: true
  next: true

bullet:
  level1: true
  level2: true

lang:
  active: true
  hide: false
  list:
  - title: Español
    path: es

  - title: English
    default: true
    path: en

versions:
  active: true
  hide: false
  list:
  - id: 1
    title: v1.0
    default: true
    file: routes-1

  - title: v2.0
    file: routes-2

# External libraries
showdown:
    noHeaderId: true
    parseImgDimensions: true
    simplifiedAutoLink: true
    excludeTrailingPunctuationFromURLs: true
    strikethrough: true
    tables: true
    tasklists: true

perfectscrollbar:
    suppressScrollX: true
    minScrollbarLength: 20
    maxScrollbarLength: 80