title: GitOwl Framework
logo: GitOwl
theme: default
redirectHome: true
nav:
  prev: true
  next: true

bullet:
  level1: true
  level2: true

lang:
  active: false
  list:
  - title: Español
    path: es

  - title: English
    path: en

versions:
  active: false
  list:
  - title: v1.0
    path: v1.0

  - title: v2.0
    path: v2.0

# External libraries
showdown:
    noHeaderId: true
    parseImgDimensions: true
    simplifiedAutoLink: true
    excludeTrailingPunctuationFromURLs: true
    strikethrough: true
    tables: true
    tasklists: true

perfectscrollbar:
    suppressScrollX: true
    minScrollbarLength: 20
    maxScrollbarLength: 80